// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/messages": {
            "get": {
                "description": "Get a list of messages filtered by their status",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "List messages by status",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Message status (e.g., PENDING, SENT)",
                        "name": "status",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/message.listByStatusResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid status parameter",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Create a new message with content and phone number",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Create a new message",
                "parameters": [
                    {
                        "description": "Message object to be created",
                        "name": "message",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/message.createRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/message.createResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/messages/jobs": {
            "post": {
                "description": "Starts the background job that sends pending messages",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Start the message sending job",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/message.startJobResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Stops the background job that sends pending messages",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "messages"
                ],
                "summary": "Stop the message sending job",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/message.stopJobResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/server.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "message.createRequest": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Hello, world!"
                },
                "phone": {
                    "type": "string",
                    "example": "+905551234567"
                }
            }
        },
        "message.createResponse": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "string",
                    "example": "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
                }
            }
        },
        "message.listByStatusResponse": {
            "type": "object",
            "properties": {
                "items": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/message.listByStatusResponseItem"
                    }
                }
            }
        },
        "message.listByStatusResponseItem": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "example": "Hello from Swagger!"
                },
                "createdAt": {
                    "type": "string",
                    "example": "2023-10-27T10:00:00Z"
                },
                "id": {
                    "type": "string",
                    "example": "a1b2c3d4e5f6g7h8i9j0k1l2m3n4o5p6"
                },
                "phone": {
                    "type": "string",
                    "example": "+905551234567"
                },
                "status": {
                    "type": "string",
                    "example": "PENDING"
                },
                "updatedAt": {
                    "type": "string",
                    "example": "2023-10-27T10:00:00Z"
                }
            }
        },
        "message.startJobResponse": {
            "type": "object",
            "properties": {
                "started": {
                    "type": "boolean"
                }
            }
        },
        "message.stopJobResponse": {
            "type": "object",
            "properties": {
                "stopped": {
                    "type": "boolean"
                }
            }
        },
        "server.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string",
                    "example": "details of the error"
                },
                "message": {
                    "type": "string",
                    "example": "Invalid request."
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:2025",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Messager API",
	Description:      "Fast & Strong Messaging Tool",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
